### ISSUE TITLE
Change repository location/name

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/website#1]
Unless this presents some difficulty, I'd prefer to keep all the code for the project under the [religious-ecologies](https://github.com/religious-ecologies) organization. (Helps with showing progress/results to funders.) I've added all the contributors as owners on that organization. And perhaps the repository should be renamed? 

How about transferring to `religious-ecologies/relec-website`?

**Comment by kalbers** [comment]
That works for me. What's the best process here?

**Comment by lmullen** [comment]
I think someone with admin access can go into settings on this repository and transfer it/rename it. I think GitHub is pretty good about maintaining redirects.

**Comment by lmullen** [comment]
Moved to [religious-ecologies/website](https://github.com/religious-ecologies/website).
