### ISSUE TITLE
Text/logos for the footer

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/website#12]
The footer should include the following elements, linked to the institutions:

- [ ] RRCHNM logo
- [ ] NEH logo

If you think there is room for the GMU logo, you can include it, but I don't think it is vital. 

The text for the footer should include the following.

> *American Religious Ecologies* is generously funded in part by the [National Endowment for the Humanities](https://www.neh.gov) and developed by the [Roy Rosenzweig Center for History and New Media](https://rrchnm.org) at [George Mason University](https://www2.gmu.edu).
> 
> [CC LOGO IF YOU WANT] This site is licensed under a [Creative Commons BY 4.0](https://creativecommons.org/licenses/by/4.0/) license.

Here are the NEH [acknowledgement guidelines](https://www.neh.gov/grants/manage/acknowledgment-and-publicity-requirements-neh-awards), which includes their logo. 

One of the things that they say is this:

> Additionally, all digital projects must incorporate the following NEH-specific keywords:
> National Endowment for the Humanities
> NEH

I don't know what they mean by that. Obviously we use them at various places in the site. Do you think they want it in the `<meta>` keywords?

**Comment by kimisgold** [comment]
@lmullen I think they do mean the meta keywords, which is easy enough. Is there anything else you'd like to include alongside the NEH keywords?

**Comment by lmullen** [comment]
Hmm. 

How about these?

- religious ecologies
- American religious history 
- Census of Religious Bodies

Feel free to use only what you think might actually have an effect.
