### ISSUE TITLE
Text for the about page

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/website#13]
Here is the text for the about page as a Markdown file. (It has a `.txt` extension because GitHub won't let you upload `.md`.)

[about.txt](https://github.com/chnm/rel-ecol-hugo-theme/files/3664407/about.txt)

@jgturner52 Could you please glance at this and see if anything needs to be changed?

**Comment by jgturner52** [comment]
Looks good!

**Comment by lmullen** [comment]
We need to add Thanh to the above since she's doing a huge amount to make the project function.
