### ISSUE TITLE
Minor design questions

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/website#18]
Here are a few minor design questions I noticed. Up to you, @kalbers and @kimisgold whether you think these should be changed.

- [x] On mobile (Chrome emulating iPhone 6/7/8 anyway) the logos look like they are overlapping.

![image](https://user-images.githubusercontent.com/183672/66077503-19770e80-e52e-11e9-9829-a88f2551302f.png)

- [x] There is a middle width, in between a narrow phone and a desktop browser, where the styles don't seem quite right. 

For instance, on portrait iPad resolution, the figures and figure captions are full width, but the body text is not.

![image](https://user-images.githubusercontent.com/183672/66077714-82f71d00-e52e-11e9-8d21-9d14f7f36ce9.png)

Or on iPhone 6/7/8 landscape, the title seems to break at an odd place, and the images are very small but the text is very large.

![image](https://user-images.githubusercontent.com/183672/66077861-de290f80-e52e-11e9-8ad5-b940babb0897.png)

- [x] At certain resolutions (e.g., iPhone 6/7/8 landscape, but others as well) the headers run into the +/- symbol.

![image](https://user-images.githubusercontent.com/183672/66077985-1c263380-e52f-11e9-9c2c-2575b7b8f492.png)

**Comment by lmullen** [comment]
One other thing.

- [ ] The accordion can get stuck if the browser is resized. For example, if the window is full width on a laptop, then is made a bit less than half width of a screen, the open element on the accordion will collapse, but the state indicated by the +/- indicator will still be as if it is expanded, and it will take two clicks on the header to "close" it and then re-expand it.

Maybe this is just an artifact of testing. But I think this would affect a mobile user who switches orientations of their device, or a desktop user with two browser windows side by side, as I often use.

**Comment by kalbers** [comment]
FWIW, I don't get the Ipad issue in either Firefox or Chrome on my machine. Could be an emulator hiccup. Should all be easier to see once it's up and we can do some real device testing.

I do get the titles overrunning as well. @kimisgold Looks like a margin-right on .accordion h2 takes care of it.

I'm a little unsure about the last issue. Probably something also worth checking on actual devices.

**Comment by kimisgold** [comment]
@lmullen I think I've addressed each of these points in my latest commits. If you find further edits needed, let's break them out into individual issues for easier tracking.
