### ISSUE TITLE
Visualizations navigation

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/website#21]

**Comment by lmullen** [comment]
@kalbers or @kimisgold: Could you please add a way for users to navigate to the visualizations? 

Should this be in the header alongside "about" and "blog"?

For the visualizations browse page (served at `/visualizations/` on the `dioceses` branch, would it make sense to remove the date? Would it make sense to have a thumbnail/preview image of each visualization along with the abstract text?

**Comment by kimisgold** [comment]
I think this should be in the header, and yes, we should give the browse its own layout distinct from the blog posts. Would you want the visualizations sorted by creation date or some other order?

**Comment by lmullen** [comment]
I think creation date is fine. We're not likely to have a huge number that would necessitate a more complicated browsing scheme.

To the question you posed in Slack, I don't foresee needing to add another heading beyond `visualizations` soon. The other possibility is `data` but that won't be for a while, and even then we might put it in the front page accordion content.

**Comment by kimisgold** [comment]
I've drafted the visualizations section of the site in the `dioceses` branch starting with 93cf39e55c9692fb10ab5adbc421b1e63ceb01f7. The commit includes the following: 

* List view with thumbnails, heading, and description
* Front matter for thumbnail file names and their screen reader descriptions
* A directory within the static files directory for visualization thumbnails
* Top navigation item for visualizations

**Comment by lmullen** [comment]
Thanks for doing this, @kimisgold. On the whole this looks great. I'll probably make a slightly different thumbnail for the dioceses map so it doesn't have the caption for the bar chart in the thumbnail of the map.

One question: In the screenshot below, there is some border around an empty image to the right of the thumbnail.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/183672/84429229-ccd3ef00-abf5-11ea-9029-e82c38fb4af9.png">

Should lines 17-19 [here](https://github.com/religious-ecologies/website/blob/dioceses/layouts/visualizations/list.html#L17) be deleted? It looks like there are two places for the thumbnail.

**Comment by lmullen** [comment]
@kimisgold Would it make sense to also feature the abstract on the visualization show page? Perhaps as a tag line of sorts? We've called it an `abstract` but I don't think it's going to be a whole paragraph; more like a sentence or phrase.
