### ISSUE TITLE
Links not keyboard accessible ANDI

### ISSUE THREAD

**Issue by csgreer6** [religious-ecologies/website#29]
On the religious ecologies homepage,
![Screen Shot 2020-10-29 at 1 47 55 PM](https://user-images.githubusercontent.com/70596028/97612246-96a0db80-19ed-11eb-816a-8c4da69f07ed.png)
![Screen Shot 2020-10-29 at 1 48 01 PM](https://user-images.githubusercontent.com/70596028/97612248-97397200-19ed-11eb-9c0e-879b3e09cc20.png)

 the "Why Religious Ecologies," "The US Census of Religious Bodies," and "New Datasets for American Religious History" have links that are not keyboard accessible. Using Andi on Mac. Images attached.

**Comment by kimisgold** [comment]
Duplicate of #26.
