### ISSUE TITLE
Link to Census Schedules Omeka site

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/website#30]
The front page should have some text that links to the Omeka site when that is released.

**Comment by lmullen** [comment]
Lincoln and John and Greta will draft some text for a new call to action block at the top. Should be organized with most important call to actions. 

Kim will then make/add the call to actions.

**Comment by lmullen** [comment]
@kimisgold I think we have an idea of what this call to action should look like, and want to run it by you. 

- We were thinking that this would go above the three existing blocks and outside of the accordion structure. But if you think it should be in the accordion structure, that's fine.
- This is what we came up with for text

------------

The American Religious Ecologies project is creating new datasets and visualizations[BLOCK 3] to study the history of American religion [BLOCK 1]. We are digitizing the 1926 Census of Religious Bodies[BLOCK 2] and other historical sources.

Browse schedules describing thousands of congregations from the 1926 Census of Religious Bodies. [LINK TO OMEKA SITE]
Use our visualizations of American religious history. [LINK TO VISUALIZATIONS TAB]
Read our blog about the history of data and American religion, as well as about our project. [LINK TO BLOG]
-----

- I was thinking that the links to the blocks in that first paragraph would open and scroll to the relevant block in the accordion.
- Does this need an image? I figured no, since the calls to action would be styled.

What do you think?

**Comment by kimisgold** [comment]
This looks like a great start. I'll draft these updates in a branch.

**Comment by kimisgold** [comment]
I ended up adding the calls to action to the accordion blocks, because it felt too redundant as separate blocks external to those. Linking to the blocks and having them expand was also a little too finicky. I've drafted this in the `home-update` branch for the time being.

**Comment by lmullen** [comment]
Thanks, Kim. I like this approach. I sent a screenshot to John so he doesn't have to deal with Hugo. More soon.

In the meantime, a weird thing. In both Safari and Firefox, if I click on the text in one of the paragraphs, a blue highlight bar appears around the entire body. Almost like something is highlighted? Screenshots to show you what I mean.

Before clicking.

<img width="1494" alt="Screen Shot 2020-12-10 at 5 25 43 PM" src="https://user-images.githubusercontent.com/183672/101837263-cecb2c00-3b0c-11eb-92c9-71c7cf770518.png">

After clicking.

<img width="1494" alt="Screen Shot 2020-12-10 at 5 25 48 PM" src="https://user-images.githubusercontent.com/183672/101837260-ce329580-3b0c-11eb-95e8-0025e973b7ac.png">

**Comment by jgturner52** [comment]
@kimisgold I like the calls to action within the accordion blocks. Looks sharp.

**Comment by lmullen** [comment]
I've updated the text throughout. I'll open a separate issue for the unwanted highlighting if it persists.
