### ISSUE TITLE
Standardize policy for small caps

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/website#4]
I like the small caps as a design element. However, I think that the mix of small and full caps in places where the text is capitalized sentence rather than title case is jarring. For example:

![image](https://user-images.githubusercontent.com/183672/65785433-61f38e00-e122-11e9-91e9-29c02f323869.png)

I think that my preference would be to use only small caps without any further capitalization everywhere that small caps appears. (l.e., to lowercase all the text, but display it in small caps.) The possible exception is the Mapping American Religious Ecologies title. 

What do you think, @kimisgold and @kalbers?

**Comment by kalbers** [comment]
I don't have a strong preference on this either way. Do you @kimisgold ?

**Comment by kimisgold** [comment]
I agree with @lmullen. I can apply the style.
