### ISSUE TITLE
Node dependency updates

### ISSUE THREAD

**Issue by hepplerj** [religious-ecologies/website#44]
These instructions don't necessarily need to end up in the README, but I do want to document a few things (if only for my own ability to recall how I fixed things) after wrestling with node for over an hour. 

1. Many of the packages currently here may need to be updated to their latest releases, including both minor and major releases. Several updates include: 

```
 autoprefixer                ^9.7.6  →  ^10.2.6     
 browser-sync               ^2.26.7  →  ^2.27.3     
 css-loader                  ^3.5.3  →   ^5.2.6     
 eslint                      ^6.8.0  →  ^7.29.0     
 eslint-config-airbnb-base  ^14.1.0  →  ^14.2.1     
 eslint-plugin-import       ^2.20.2  →  ^2.23.4     
 gulp                        ^4.0.0  →   ^4.0.2     
 gulp-load-plugins           ^2.0.3  →   ^2.0.7     
 gulp-postcss                ^8.0.0  →   ^9.0.0     
 gulp-sass                   ^4.0.1  →   ^5.0.0     
 style-loader                ^1.2.0  →   ^3.0.0     
 webpack                    ^4.43.0  →  ^5.41.0     
 webpack-cli                ^3.3.11  →   ^4.7.2     
 d3                         ^5.16.0  →   ^7.0.0     
 foundation-sites            ^6.6.2  →   ^6.6.3     
 jquery                      ^3.4.1  →   ^3.6.0     
 motion-ui                   ~2.0.0  →   ~2.0.3     
 what-input                  ^5.1.2  →  ^5.2.10 
```

2. We can check the above information using the [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) package. This is installed  globally by `npm -g npm-check-updates`. Then you can run `ncu -u` in the directory to implement updates to modules. **Note that this will make changes to `package.json`**.

3. Now you can run `npm install` to install new versions, and `npm audit` to look for fixes / `npm audit fix --force` to force fixes.

In my testing so far, the only thing these updates seem to break is the mouseover events on points on the Catholic diocese map: the pop-up no longer follows the mouse pointer, but this should be fairly easy fix (this *might* even be an issue with my own computer, I'm investigating.)

**Comment by hepplerj** [comment]
Just a few more notes as I investigate issues I'm dealing with regarding Node, `nvm`, and `npm`. 

- It appears older versions of Node (e.g., anything under v15) simply don't compile on Apple's M1 / aarch64 architecture. 
- The work-around in the event we would need older versions of Node on an M1 machine will likely need to use [Rosetta 2](https://support.apple.com/en-us/HT211861) (in Terminal or iTerm) and set the architecture to `arch -x86_64 zsh`. 

**I haven't tested this yet on my own machine**, but this seems to be the way to make this work if we need it. It might be worthwhile, though, to go head and update packages and Node as outlined above going forward.

**Comment by lmullen** [comment]
@hepplerj I'm fine with upgrading the dependencies if you would like. And certainly, once the Node version changes lots of things get temperamental. Basically all of those dependencies (except Webpack and D3) relate to the Foundation theme and compiling it from SCSS.

**Comment by lmullen** [comment]
The implication being, that we might be able to remove many of those dependencies if now the stylesheet assets are also being compiled directly by Hugo.

**Comment by hepplerj** [comment]
Makes sense. Let me dig in and see what we might be able to prune from the node dependencies. I'll probably fold this issue in with #47 too, that way we can update both D3 and these depencies in a single branch rather than complicate it unnecessarily.

In other words, we can probably resolve both issues at once after I update everything.
