### ISSUE TITLE
Makefile out of date

### ISSUE THREAD

**Issue by hepplerj** [religious-ecologies/website#45]
The `--display` flag isn't supported by webpack any longer and should be removed from the makefile.

**Comment by lmullen** [comment]
Do you want to do this, @hepplerj, or do you want me to?

I'd really love to just use Hugo's built-in bundling (#23) instead of using Webpack, which would supersede this issue if we do that.

**Comment by hepplerj** [comment]
I sure can, but I'm also fine moving this over to Hugo's built-in bundling instead. Since Hugo is handling the website anyway, I'm all for removing any extra overhead and using the built-in tools.

**Comment by lmullen** [comment]
Is this a problem for building things now?

My attitude towards dependencies in cases like these is that it doesn't really matter if there is an update or a security flaw. The code is only run locally (apart from front-end dependencies), and the static site means there isn't a threat. So if it works with whatever is in `package.json` we can just handle upgrading everything all at once when we are ready.

**Comment by hepplerj** [comment]
I think things are fine for now. 

I'm having difficulty building locally, but that doesn't mean the site as a whole has an issue. I'm not exactly sure yet what I'm running in to (seems like it might be related to `libsass`/`node-sass` -- and I'm doing all of this on a brand new machine, so it could be I need to downgrade a compiler or macOS moved things around on me or something).

**Comment by hepplerj** [comment]
PR #46 resolved this, closing.
