### ISSUE TITLE
Update to the latest version of D3?

### ISSUE THREAD

**Issue by hepplerj** [religious-ecologies/website#47]
In response to #44 it might be worth the effort to update the Catholic dioceses map to work with the latest version of D3 ([v7](https://d3js.org)) so we can use the latest features in future maps and visualizations. In my testing so far, this does break a few things that will need to be fixed (I'll update this list when/if I find other issues): 

- [x] The ability to zoom on the map no longer works. The behavior we get after updating is the points resize and the map recenters, but no actual zooming happens. Likely just an update in the D3 API. 
- [x] Hovering over points for pop-ups no longer works, which seems to be connected to `d3.event` being depreciated. This is a simple fix. 
- [x] The data contained in the mouseover pop-ups are `undefined`, which is also connected to API changes in D3.

**Comment by lmullen** [comment]
Now that we've closed #46, I'm fine with moving to d3 v7. (It's had a lot of version increments recently!)

**Comment by lmullen** [comment]
Pretty sure this was closed by #49.
