### ISSUE TITLE
Changes to functionality of the accordion

### ISSUE THREAD

**Issue by lmullen** [religious-ecologies/website#7]
- Currently, the scrolling for the accordion seems off. The jump from activating a different section disorients the reader. (Hard to describe but I can show you if you prefer.) Can this be smoother?

- Should the user be able to collapse all of the content blocks or should one always remain currently open?

- Should all the blocks be collapsed by default when the page is loaded on mobile?

**Comment by kalbers** [comment]
Add data-multi-expand="true" and data-allow-all-closed="true" to fix.

**Comment by kalbers** [comment]
remove .is-active on mobile

**Comment by kalbers** [comment]
I pushed a change up to allow them all to be open or closed. Do we think we still need them all collapsed to start for mobile or no?

**Comment by lmullen** [comment]
I’ll let you and Kim decide what you think is best.
